// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBahTY2RLq5LzHCs9y7zJrDG583S9J1c6I',
    appId: '1:749080332708:web:eefa648618493563a09931',
    messagingSenderId: '749080332708',
    projectId: 'cicd-f7aa6',
    authDomain: 'cicd-f7aa6.firebaseapp.com',
    storageBucket: 'cicd-f7aa6.firebasestorage.app',
    measurementId: 'G-MLKNQGHV5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeY7qCVyODS7M6A2aQ8ALK_noW7YOvX1w',
    appId: '1:749080332708:android:49981388274c782ea09931',
    messagingSenderId: '749080332708',
    projectId: 'cicd-f7aa6',
    storageBucket: 'cicd-f7aa6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8HF8auinq-A3pPETGNtQUYLtXDUv1Z6E',
    appId: '1:749080332708:ios:ef12c690e3d623bea09931',
    messagingSenderId: '749080332708',
    projectId: 'cicd-f7aa6',
    storageBucket: 'cicd-f7aa6.firebasestorage.app',
    iosBundleId: 'com.example.testCiCd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8HF8auinq-A3pPETGNtQUYLtXDUv1Z6E',
    appId: '1:749080332708:ios:ef12c690e3d623bea09931',
    messagingSenderId: '749080332708',
    projectId: 'cicd-f7aa6',
    storageBucket: 'cicd-f7aa6.firebasestorage.app',
    iosBundleId: 'com.example.testCiCd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBahTY2RLq5LzHCs9y7zJrDG583S9J1c6I',
    appId: '1:749080332708:web:b40a74874909b2b3a09931',
    messagingSenderId: '749080332708',
    projectId: 'cicd-f7aa6',
    authDomain: 'cicd-f7aa6.firebaseapp.com',
    storageBucket: 'cicd-f7aa6.firebasestorage.app',
    measurementId: 'G-BBVN09QC45',
  );

}